<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SKD8PO3" failures="1" tests="8" name="Test" time="0.062" errors="0" timestamp="08 Apr 2025 14:45:32 GMT">
  <testcase classname="testng.FailedTest2" name="d" time="0.013"/>
  <testcase classname="testng.FailedTest2" name="e" time="0.002"/>
  <testcase classname="testng.FailedTest2" name="f" time="0.002"/>
  <testcase classname="testng.FailedTest2" name="user" time="0.006">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="testng.FailedTest2" name="user" time="0.001">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="testng.FailedTest2" name="user" time="0.001">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="testng.FailedTest2" name="user" time="0.001">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="testng.FailedTest2" name="user" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [grace] but found [Grace]">
      <![CDATA[java.lang.AssertionError: expected [grace] but found [Grace]
	at testng.FailedTest2.user(FailedTest2.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- user -->
</testsuite> <!-- Test -->
